export const OPENROUTER_MODELS = [
    // Premium Models
    'openai/gpt-4o',
    'openai/gpt-4o-mini',
    'openai/gpt-4-turbo',
    'openai/gpt-4',
    'openai/gpt-3.5-turbo',
    'anthropic/claude-3.5-sonnet',
    'anthropic/claude-3-opus',
    'anthropic/claude-3-sonnet',
    'anthropic/claude-3-haiku',
    'google/gemini-pro-1.5',
    'google/gemini-pro',
    'google/gemini-flash-1.5',
    'meta-llama/llama-3.1-405b-instruct',
    'meta-llama/llama-3.1-70b-instruct',
    'meta-llama/llama-3-70b-instruct',
    'meta-llama/llama-3-8b-instruct',
    // Free Models
    'gryphe/mythomist-7b:free',
    'mistralai/mistral-7b-instruct:free',
    'google/gemini-flash-1.5:free',
    'google/gemini-pro:free',
    'meta-llama/llama-3.2-3b-instruct:free',
    'meta-llama/llama-3.1-8b-instruct:free',
    'qwen/qwen-2.5-7b-instruct:free',
    'qwen/qwen-2-7b-instruct:free',
    'huggingface/zephyr-7b-beta:free',
    'openchat/openchat-7b:free',
    'undi95/toppy-m-7b:free',
    'goliath/120b:free',
    'openai/gpt-oss-20b:free',
    'openrouter/auto',
]
